=== igorkan45/Workspace/BookDataBase/bin/libschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.it-academy.by/periodicals" xmlns:tns="http://www.it-academy.by/periodicals"
	elementFormDefault="qualified">



	<xs:element name="periodical_item" type="tns:periodicals1" />

	<xs:complexType name="periodicals1">
		<xs:sequence>
			<xs:element name="magazine" type="tns:magazine" maxOccurs="unbounded" minOccurs="1"></xs:element>
			<xs:element name="newspaper" type="tns:newspaper" maxOccurs="unbounded" minOccurs="1"></xs:element>
			<xs:element name="books" type="tns:book" maxOccurs="unbounded" minOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"></xs:attribute>
	</xs:complexType>




	<xs:complexType name="periodicals">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
			<xs:element name="price" type="xs:int" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="magazine">
		<xs:complexContent>
			<xs:extension base="tns:periodicals">
				<xs:sequence>

					<xs:element name="editorName" type="xs:string" />
					<xs:element name="periodOfPrint" type="xs:int" />

				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="newspaper">
		<xs:complexContent>
			<xs:extension base="tns:periodicals">
				<xs:sequence>

					<xs:element name="editorName" type="xs:string" />
					<xs:element name="publisher" type="xs:string" />

				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


	<xs:complexType name="book">
		<xs:complexContent>
			<xs:extension base="tns:periodicals">
				<xs:sequence>

					<xs:element name="authorName" type="xs:string" />
					<xs:element name="periodOfPrint" type="xs:string" />
					<xs:element name="paperFormat" type="xs:string" />
					<xs:element name="additionalInfo" type="xs:string" />

				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>


</xs:schema>

=== igorkan45/Workspace/BookDataBase/resources/Library.xml
<?xml version="1.0" encoding="UTF-8"?>

<periodical_item xmlns = "http://www.it-academy.by/periodicals"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation = "http://www.it-academy.by/periodicals libschema.xsd">

	<magazine id="1">
		<title>magazine1</title>
		<pages>50</pages>
		<price>50</price>
		<editorName>Editor1</editorName>
		<periodOfPrint>1</periodOfPrint>
	</magazine>
	
	<newspaper id="2">
		<title>newspaper1</title>
		<pages>15</pages>
		<price>15</price>
		<editorName>Editor1</editorName>
		<publisher>Publisher1</publisher>
	</newspaper>
	
	<book id="3">
		<title>book1</title>
		<pages>150</pages>
		<price>100</price>
		<authorName>Author</authorName>
		<periodOfPrint>Year</periodOfPrint>
		<paperFormat>A4</paperFormat>
		<additionalInfo>Info1</additionalInfo>
	</book>



</periodical_item>
